### ISSUE TITLE
Make code blocks scrollable in the API docs 

### ISSUE THREAD

**Issue by WaelShaikh** [playcanvas/developer.playcanvas.com#129]
When I’m accessing the API docs on my phone the code blocks are sometimes pretty long and the code block isn’t scrollable so I can’t see the entire code

**Comment by willeastcott** [comment]
Seems to scroll ok on my iPhone.

https://user-images.githubusercontent.com/697563/220735068-265443d1-1839-4f83-af9e-ce5bf2f7f210.MP4

Perhaps this has been fixed since this issue was logged. Therefore, I'm closing. But if anyone finds that scrolling code still doesn't work for them, feel free to reopen the issue.
