### ISSUE TITLE
Add equirect hdri's to cubemaps tool

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#284]
Great tool found by Martin: https://jamie-white.com/webgl/equirectangular-hdr-image-to-face-list/

**Comment by Maksims** [comment]
I've used that tool for conversions since we had cubemap support in the engine.
Also, worth investigating as cmftStudio is built on top of [cmft](https://github.com/dariomanesku/cmft) - which is a command-line tool, and potentially can be used through the pipeline - offering nice tools for conversions in Editor.

**Comment by yaustar** [comment]
Another tool: https://matheowis.github.io/HDRI-to-CubeMap/
