### ISSUE TITLE
ScriptType in API Reference is at the end

### ISSUE THREAD

**Issue by Maksims** [playcanvas/developer.playcanvas.com#35]
http://developer.playcanvas.com/en/api/ScriptType.html
On left panel, it is not sorted with others.

**Comment by willeastcott** [comment]
This is because the list is really lots of pc.<Class> entries. ScriptType is unusual because it is not declared in the pc namespace (for some reason). For readability in the API reference class list, we hide the 'pc.' But the current order is 'correct'. An easy way to resolve this is to update the API ref docs to declare ScriptType in the pc namespace. Unless anyone complains, I'll do that when I get a second.

**Comment by vkalpias** [comment]
ScriptType is not a pc class. It's basically used as a concept to describe
the type of thing that is returned from pc.createScript.

The thing that is returned is a constructor not an instance of ScriptType.

**Comment by willeastcott** [comment]
Do you have a suggestion on how to resolve this then? Also looping in @daredevildave.

**Comment by vkalpias** [comment]
We can probably set the order in the build script. Need to take a look at
it.

**Comment by willeastcott** [comment]
Fixed by recent work done by @aidinabedi. See here: https://github.com/playcanvas/engine/pull/1710
